// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9b04a586-fe36-4e08-b5c0-964712d96e10",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_w8WoLTyrx",
    "aws_user_pools_web_client_id": "2t4j51uk4g8shh71aneiv12bvs",
    "aws_appsync_graphqlEndpoint": "https://36oqk6agefhonjpco4znmb5fce.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
